### ISSUE TITLE
Speaker Schedule

### ISSUE THREAD

**Issue by denhamparry** [CloudNativeWales/Meetups#8]
Would be good to have an open document / calendar for speakers to see which dates we have available.  Any ideas for a solution to this?

**Comment by alljames** [comment]
Something like this?

| Meetup    | Location            | Date       | Speaker Confirmed                                                   |
| ----------| :------------------ | :-----     | --------------------------------------------------------------------|
| 0.1.0     | DevOpsGuys,Cardiff  | 2018.05.10 | <ul><li>- [x] S1</li><li>- [x] S2</li><li>- [ ] :zap: talk</li></ul>|
| 0.2.0     | DevOpsGuys,Cardiff  | 2018.06.20 | <ul><li>- [x] S1</li><li>- [x] S2</li><li>- [ ] :zap: talk</li></ul>|
| 0.3.0     | DevOpsGuys,Cardiff  | 2018.07.05 | <ul><li>- [x] S1</li><li>- [x] S2</li><li>- [ ] :zap: talk</li></ul>|
| 0.4.0     | DevOpsGuys,Cardiff  | 2018.08.09 | <ul><li>- [x] S1</li><li>- [x] S2</li><li>- [ ] :zap: talk</li></ul>|
| 0.5.0     | DevOpsGuys,Cardiff  | 2018.09.13 | <ul><li>- [ ] S1</li><li>- [ ] S2</li><li>- [ ] :zap: talk</li></ul>|
| 0.6.0     | DevOpsGuys,Cardiff  | 2018.10.11 | <ul><li>- [ ] S1</li><li>- [ ] S2</li><li>- [ ] :zap: talk</li></ul>|
| 0.7.0     | DevOpsGuys,Cardiff  | 2018.11.08 | <ul><li>- [ ] S1</li><li>- [ ] S2</li><li>- [ ] :zap: talk</li></ul>|
| 0.8.0     | DevOpsGuys,Cardiff  | 2018.12.13 | <ul><li>- [ ] S1</li><li>- [ ] S2</li><li>- [ ] :zap: talk</li></ul>|
| 0.9.0     | DevOpsGuys,Cardiff  | 2019.01.10 | <ul><li>- [ ] S1</li><li>- [ ] S2</li><li>- [ ] :zap: talk</li></ul>|
| 0.10.0    | DevOpsGuys,Cardiff  | 2019.02.14 | <ul><li>- [ ] S1</li><li>- [ ] S2</li><li>- [ ] :zap: talk</li></ul>|
| 0.11.0    | DevOpsGuys,Cardiff  | 2019.03.14 | <ul><li>- [ ] S1</li><li>- [ ] S2</li><li>- [ ] :zap: talk</li></ul>|
| 0.12.0    | DevOpsGuys,Cardiff  | 2019.04.11 | <ul><li>- [ ] S1</li><li>- [ ] S2</li><li>- [ ] :zap: talk</li></ul>|
| 0.13.0    | TBC                 | 2019.05.09 | <ul><li>- [ ] S1</li><li>- [ ] S2</li><li>- [ ] :zap: talk</li></ul>|
| 0.14.0    | TBC                 | 2019.06.13 | <ul><li>- [ ] S1</li><li>- [ ] S2</li><li>- [ ] :zap: talk</li></ul>|
| 0.15.0    | TBC                 | 2019.07.11 | <ul><li>- [ ] S1</li><li>- [ ] S2</li><li>- [ ] :zap: talk</li></ul>|
| 0.16.0    | TBC                 | 2019.08.08 | <ul><li>- [ ] S1</li><li>- [ ] S2</li><li>- [ ] :zap: talk</li></ul>|
| 0.17.0    | TBC                 | 2019.09.12 | <ul><li>- [ ] S1</li><li>- [ ] S2</li><li>- [ ] :zap: talk</li></ul>|
| 0.18.0    | TBC                 | 2019.10.10 | <ul><li>- [ ] S1</li><li>- [ ] S2</li><li>- [ ] :zap: talk</li></ul>|
| 0.19.0    | TBC                 | 2019.11.14 | <ul><li>- [ ] S1</li><li>- [ ] S2</li><li>- [ ] :zap: talk</li></ul>|
| 0.20.0    | TBC                 | 2019.12.12 | <ul><li>- [ ] S1</li><li>- [ ] S2</li><li>- [ ] :zap: talk</li></ul>|

**Comment by denhamparry** [comment]
@alljames, take my money!!!
